import localFont from 'next/font/local'
import './globals.css'

const RepublicaMinor = localFont({
	src: './fonts/Republica Minor 2.0.otf',
	variable: '--font-republica-minor',
	weight: '900'
})

export const metadata = {
	title: 'DaoPVT • Web Developer',
	// Replace with actual description
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${RepublicaMinor.variable} antialiased`}>
				{children}
			</body>
		</html>
	)
}
